---
- name: "Get ceph config dump"
  tags:
    - ceph.dump
    - ceph.dump.config
  ansible.builtin.command: ceph config dump --format json
  become: true
  run_once: true
  register: ceph_dump_config

- name: "Get ceph config fsid"
  tags:
    - ceph.dump
    - ceph.dump.config
  ansible.builtin.command: ceph fsid
  become: true
  run_once: true
  register: ceph_dump_fsid

- name: "Get ceph config version"
  tags:
    - ceph.dump
    - ceph.dump.config
  ansible.builtin.command: ceph version
  become: true
  run_once: true
  register: ceph_dump_version

- name: "Get ceph pool dump"
  tags:
    - ceph.dump
    - ceph.dump.pool
  ansible.builtin.command: ceph osd dump --format json
  become: true
  run_once: true
  register: ceph_dump_pool

- name: "Get ceph osd df"
  tags:
    - ceph.dump
    - ceph.dump.osd
  ansible.builtin.command: ceph osd df --format json
  become: true
  run_once: true
  register: ceph_dump_osd
