---
- ansible.builtin.import_tasks: directory.yaml

- name: "Setup keyrings"
  ansible.builtin.template:
    src: keyring.ji2
    dest: "{{ item['path'] | default(ceph_keyring['path']) }}"
    owner: "{{ item['owner'] | default(ceph_keyring['owner']) }}"
    group: "{{ item['group'] | default(ceph_keyring['group']) }}"
    mode: "{{ item['mode'] | default(ceph_keyring['mode']) }}"
    setype: "{{ item['setype'] | default(ceph_keyring['setype']) }}"
  loop: "{{ ceph_keyrings }}"
  loop_control:
    label: "{{ item['name'] }} path={{ item['path'] | default(ceph_keyring['path']) }}"
